name: CI-CD

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  tests:

    name: Python ${{ matrix.python }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    timeout-minutes: 10

    strategy:
      fail-fast: true

      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python: ["3.10"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Dependencies
        run: pip install -r requirements.txt

      - name: Tests
        run: pytest
  deploy:
    needs: tests

    name: Deploy into production branch

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Merge main into prod
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: prod
          github_token: ${{ github.token }}
